// JavaScript Document
var ChannelName = new Array(); //Channel Name;
ChannelName[0] = "CCTV-1";
ChannelName[1] = "BEI JING TV-5";
ChannelName[2] = "TIAN JIN TV-1";
ChannelName[3] = "SHANG HAI NEWS TV";
ChannelName[4] = "HU HE HAO TE TV";
ChannelName[5] = "LIAO NING DA LIAN TV-2";
ChannelName[6] = "USA LIFE TV";
ChannelName[7] = "HEI LONG JIANG TV-1";
ChannelName[8] = "FENG HUANG WEI SHI";
ChannelName[9] = "CCTV-12";
ChannelName[10] = "LIAO NING TV";
ChannelName[11] = "CCTV-MOVIE";
ChannelName[12] = "BBC-NEWS";
ChannelName[13] = "SHANG HAI TV";
ChannelName[14] = "HONG KONG NEWS";
var ChannelInfor = new Array();
ChannelInfor[0] = "Marty McFly is your average, slacker teenager, who is friendly with a wacky inventor named Doc Brown.";
ChannelInfor[1] = "Where he develops a friendship with the grandfatherly projectionist, Alfredo, who takes a shine to the young boy and often lets him watch movies in the projection booth.";
ChannelInfor[2] = "Hallie Parker and Annie James (played by Lindsey Lohan) are identical twins separated at a young age because of their parents' divorce.";
ChannelInfor[3] = "The bulk of the film takes place in this flashback, which takes place shortly after World War II. We meet Salvatore.";
ChannelInfor[4] = "The story follows the life of low I.Q. Forrest Gump and his meeting with the love of his life Jenny.";
ChannelInfor[5] = "Remy is a rat, constantly risking life in an expensive French restaurant because of his love of good food, as well as a desire to become a chef.";
ChannelInfor[6] = "Hallie Parker and Annie James (played by Lindsey Lohan) are identical twins separated at a young age because of their parents' divorce.";
ChannelInfor[7] = "The bulk of the film takes place in this flashback, which takes place shortly after World War II. We meet Salvatore.";
ChannelInfor[8] = "Hallie meets her mother, and Annie meets her father for the first time in years. they then make a plan to set up their parents, which suddenly goes awry with an announcement from their father.";
ChannelInfor[9] = "We watch Salvatore woo--and win--Elena's heart, only to lose her due to her father's disapproval. As Elena and her family move away, Salvatore leaves town to serve his compulsory military service.";
ChannelInfor[10] = "In 1947, a banker named Andrew 'Andy' Dufresne (Tim Robbins) is convicted of murdering his wife and her lover, based on strong circumstantial evidence.";
ChannelInfor[11] = "In the 154-minute version of the film, Salvatore returns to Rome and happens upon a young girl who looks so similar to the teenaged Elena that she can only be a relative.";
ChannelInfor[12] = "Where he develops a friendship with the grandfatherly projectionist, Alfredo, who takes a shine to the young boy and often lets him watch movies in the projection booth.";
ChannelInfor[13] = "We watch Salvatore woo--and win--Elena's heart, only to lose her due to her father's disapproval.";
ChannelInfor[14] = "The story goes through many different twists and turns, and is an amazing story from start to finish.";
var ChannelAdd = new Array(); // Channel IP;  
ChannelAdd[0] = "225.1.2.249:30120";
ChannelAdd[1] = "225.1.1.249:30120";
ChannelAdd[2] = "225.1.2.247:30120";
ChannelAdd[3] = "225.1.2.245:30120";
ChannelAdd[4] = "225.1.1.153:30120";
ChannelAdd[5] = "225.1.1.193:30120";
ChannelAdd[6] = "225.1.1.192:30120";
ChannelAdd[7] = "225.1.1.192:30120";
ChannelAdd[8] = "239.255.0.3:5001";
ChannelAdd[9] = "239.255.0.4:5001";
ChannelAdd[10] = "239.255.0.5:5001";
ChannelAdd[11] = "239.255.0.6:5001";
ChannelAdd[12] = "239.255.0.7:5001";
ChannelAdd[13] = "239.255.0.8:5001";
ChannelAdd[14] = "239.255.0.9:5001";

/****************************************** Tips Text ***************************************/ 
var TipsTxtArr = new Array();
TipsTxtArr[0] = " Stop Recording"
TipsTxtArr[1] = " Stop Recording"
TipsTxtArr[2] = " Stop Time shifting"
TipsTxtArr[3] = " Stop Time shifting"
TipsTxtArr[4] = " HDD Filled, Recording Failed"
TipsTxtArr[5] = " Stop Time shifting"
TipsTxtArr[6] = " Input Wrong, Please Retry";